### ISSUE TITLE
WARNING: Inline strong start-string without end-string.

### ISSUE THREAD

**Issue by Tridu33** [manim-kindergarten/manim_document_zh#15]
使用最新版manim命令`make html`后警告：

···
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyMethod:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyMethod:1: WARNING: Inline strong start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyPointwiseFunction:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyPointwiseFunction:1: WARNING: Inline strong start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyPointwiseFunctionToCenter:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyPointwiseFunctionToCenter:1: WARNING: Inline strong start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.FadeToColor:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.FadeToColor:1: WARNING: Inline strong start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ScaleInPlace:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ScaleInPlace:1: WARNING: Inline strong start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ShrinkToCenter:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ShrinkToCenter:1: WARNING: Inline strong start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.Restore:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.Restore:1: WARNING: Inline strong start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyMatrix:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyMatrix:1: WARNING: Inline strong start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyComplexFunction:1: WARNING: Inline emphasis start-string without end-string.
...\manim\manimlib\animation\transform.py:docstring of manimlib.animation.transform.ApplyComplexFunction:1: WARNING: Inline strong start-string without end-string.
···

**Comment by Tridu33** [comment]
查看...\manim\manimlib\animation\transform.py注释发现
```
class ApplyMethod(Transform):
    def __init__(self, method, *args, **kwargs):
        r"""
        method is a method of Mobject, *args are arguments for
        that method.  Key word arguments should be passed in
        as the last arg, as a dict, since **kwargs is for
        configuration of the transform itself

        Relies on the fact that mobject methods return the mobject
        """
```

修改为；

```
class ApplyMethod(Transform):
    def __init__(self, method, *args, **kwargs):
        r"""
        method is a method of Mobject, \*args are arguments for
        that method.  Key word arguments should be passed in
        as the last arg, as a dict, since \*\*kwargs is for
        configuration of the transform itself

        Relies on the fact that mobject methods return the mobject
        """
```

即可。
想知道有没有别的方法既能保持"""中直接写*符号"""的便捷，make html又不会warning的方法。

**Comment by TonyCrane** [comment]
manim里面的文档字符串都不太符合Sphinx的规范，所以会有很多Warning。
所以我生成这个文档的时候用的是这个：https://github.com/manim-kindergarten/manim_document_zh/blob/manim/
