### ISSUE TITLE
manim.ml 网站 不能访问了

### ISSUE THREAD

**Issue by panda8z** [manim-kindergarten/manim_document_zh#19]
manim.ml 网站 不能访问了

**Comment by Tridu33** [comment]
QQ群（862671480）群公告有说到“域名过期了”，现在直接从readme.md的链接进去吧。

**Comment by chenxuuu** [comment]
> 
> 
> QQ群（862671480）群公告有说到“域名过期了”，现在直接从readme.md的链接进去吧。

`CNAME`文件还在那里放着，链接有啥用

```bash
sh$ curl https://manim-kindergarten.github.io/manim_document_zh/ -I
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 162
Server: GitHub.com
Content-Type: text/html
x-origin-cache: HIT
Location: https://manim.ml/
X-GitHub-Request-Id: 9F2C:27E3:E9A01:11EAE6:605D5162
Accept-Ranges: bytes
Date: Fri, 26 Mar 2021 03:13:42 GMT
Via: 1.1 varnish
Age: 4
X-Served-By: cache-hnd18751-HND
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1616728423.777081,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: 53066d5a7f776dfb731a9194cc3faac7c166fbc1
```

**Comment by TonyCrane** [comment]
> > QQ群（862671480）群公告有说到“域名过期了”，现在直接从readme.md的链接进去吧。
> 
> `CNAME`文件还在那里放着，链接有啥用
> 
> ```shell
> sh$ curl https://manim-kindergarten.github.io/manim_document_zh/ -I
> HTTP/1.1 301 Moved Permanently
> Connection: keep-alive
> Content-Length: 162
> Server: GitHub.com
> Content-Type: text/html
> x-origin-cache: HIT
> Location: https://manim.ml/
> X-GitHub-Request-Id: 9F2C:27E3:E9A01:11EAE6:605D5162
> Accept-Ranges: bytes
> Date: Fri, 26 Mar 2021 03:13:42 GMT
> Via: 1.1 varnish
> Age: 4
> X-Served-By: cache-hnd18751-HND
> X-Cache: HIT
> X-Cache-Hits: 1
> X-Timer: S1616728423.777081,VS0,VE0
> Vary: Accept-Encoding
> X-Fastly-Request-ID: 53066d5a7f776dfb731a9194cc3faac7c166fbc1
> ```

不好意思，刚看到这个。可能他无意间添回来了。现在删掉了
