### ISSUE TITLE
有关"常见问题"的页面均无法正常打开

### ISSUE THREAD

**Issue by AprilNEA** [manim-kindergarten/manim_document_zh#23]
有关"常见问题"的页面均无法正常打开，包括:
- [教程文档首页的常见问题](https://docs.manim.org.cn/index.html?highlight=%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%AF%A6%E8%A7%81%20FAQ)
- [Tex 的常见问题](https://docs.manim.org.cn/documentation/mobject/svg/tex_mobject.html?highlight=%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

在作者自行部署的网页中，也没有发现相关内容，故无法做出修改。

**Comment by TonyCrane** [comment]
https://manim.org.cn/docs 哦你可以在这里看
稍等我改下域名
